# Generated by Django 5.0.4 on 2024-05-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='listing',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
