# Generated by Django 5.0.4 on 2024-05-19 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_useraccount_bio_useraccount_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='address',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='company',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='facebook_account',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='linkedin_account',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='twitter_account',
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('experience', models.SmallIntegerField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_account', models.URLField(blank=True, null=True)),
                ('linkedin_account', models.URLField(blank=True, null=True)),
                ('twitter_account', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
